### ISSUE TITLE
Behaviour when an invalid UUID is given in the URL

### ISSUE THREAD

**Issue by chrisapplegate** [yunojuno/django-user-visit#14]
Hi there,

First off - thanks for writing this plugin, it's very useful and exactly fits the use case I need it for.

I've noticed that when a URL with an invalid UUID is in the URL query string, at the moment the VisitorRequestMiddleware's `__get__` method will throw a Django `ValidationError`, thrown by the call to `Visitor.objects.get`. This ultimately results in a 500 error on the server and passed all the way through to the client. This is popping up in my error logs a few times, mostly when copy & paste has gone wrong on the client's side.

I was wondering if it would be better to return the default call to `self.get_response`, like when `InvalidVisitorPass` is thrown, instead?  I am happy to write the patch for this and PR it (at the moment I've just written my own class that inherits & wraps the method to catch the additional exception) but thought I should check in here first.

**Comment by hugorodgerbrown** [comment]
Hi @chrisapplegate thanks for this. That's an interesting scenario - if a user does paste in an invalid uuid - what do you want to happen? For us we would typically want it to fail hard _if the request cannot be completed_ so that a.) we see it in Sentry, and b.) our support team can help out (by creating a new token, or looking up the correct one). 

I appreciate that the fact that we return a 403 (most likely) if the pass exists but is invalid, makes this a grey area. I'm in two minds.

(Also - I believe you're in the wrong project - this issue is for `django-visitor-pass`, not `django-user-visit` - too many visitors ;-))

**Comment by hugorodgerbrown** [comment]
I think perhaps raising a 400 with an appropriate message may be a better way to go?

**Comment by chrisapplegate** [comment]
Hi @hugorodgerbrown. Funnily enough it was the Sentry errors annoying me that caused me to raise this :)

I agree - I think a 4xx code (i.e. "the user has messed up") rather than 5xx ("the server has messed up") is more appropriate. Current behaviour in `django-visitor-pass` for an existing pass that is invalid or expired, is that the session is created without a visitor at all, returning 200 not 403, failing silently. So to be consistent I thought serving the request but do not set up a visitor was the best fit. 

And yes I posted this in the wrong project, I'll raise an issue in the correct one & reference this one :)
